import React, { useState } from 'react';
import { ActivityIndicator, Image, Linking, Pressable, Text, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useColors } from '@/hooks/useColors';
import { searchMovies, MovieResult } from '@/services/liveApi';
import { useLife } from '@/context/LifeContext';
import { AppButton, Card, Field, Screen, SectionTitle, styles } from '@/components/ui';

export default function MoviesScreen(){
 const colors=useColors(); const {mediaFavorites,isMediaFavorite,toggleMediaFavorite,mediaHistory}=useLife();
 const [query,setQuery]=useState(''); const [results,setResults]=useState<MovieResult[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const doSearch=async()=>{if(!query.trim())return;setLoading(true);setError('');try{setResults(await searchMovies(query));}catch(e:any){setError(e?.message||'Не удалось загрузить фильмы. Проверьте TMDB access token.');}finally{setLoading(false)}};
 const favorite=(m:MovieResult)=>toggleMediaFavorite({id:String(m.id),kind:'movie',title:m.title,subtitle:m.releaseDate?.slice(0,4)||'Фильм',image:m.poster,url:m.tmdbUrl,externalId:String(m.id)});
 return <Screen>
  <Text style={[styles.eyebrow,{color:colors.primary}]}>MOVIES</Text><Text style={[styles.sectionTitle,{color:colors.foreground,fontSize:32}]}>Кино</Text>
  <Text style={{color:colors.mutedForeground,marginTop:6}}>Каталог и трейлеры через TMDB. Фильм открывается через официальный источник, без пиратских потоков.</Text>
  <View style={{flexDirection:'row',gap:8,marginTop:18}}><Field value={query} onChangeText={setQuery} placeholder="Название фильма…" style={{flex:1}}/><Pressable onPress={doSearch} style={{width:50,height:50,borderRadius:14,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'}}><Feather name="search" size={20} color={colors.primaryForeground}/></Pressable></View>
  {loading&&<ActivityIndicator style={{marginTop:20}} color={colors.primary}/>} {error?<Card style={{marginTop:16}}><Text style={{color:colors.destructive,fontWeight:'600'}}>TMDB не подключён или вернул ошибку.</Text><Text style={{color:colors.mutedForeground,marginTop:6}}>{error}</Text><Text style={{color:colors.mutedForeground,marginTop:8,fontSize:12}}>Добавьте EXPO_PUBLIC_TMDB_ACCESS_TOKEN в Secrets окружения.</Text></Card>:null}
  {results.length>0&&<><SectionTitle title="Результаты"/><View style={{gap:12}}>{results.map(m=><Card key={m.id} style={{padding:12}}><Pressable onPress={()=>router.push({pathname:'/movie/[id]',params:{id:String(m.id)}})}><View style={{flexDirection:'row',gap:12}}>{m.poster?<Image source={{uri:m.poster}} style={{width:88,height:132,borderRadius:10}}/>:<View style={{width:88,height:132,borderRadius:10,backgroundColor:colors.secondary}}/>}<View style={{flex:1}}><Text style={{color:colors.foreground,fontWeight:'700',fontSize:17}}>{m.title}</Text><Text style={{color:colors.mutedForeground,marginTop:5}}>{m.releaseDate?.slice(0,4)||'—'} · ⭐ {m.rating.toFixed(1)}</Text><Text numberOfLines={4} style={{color:colors.mutedForeground,lineHeight:19,marginTop:10}}>{m.overview||'Описание отсутствует.'}</Text></View></View></Pressable><View style={{flexDirection:'row',gap:8,marginTop:12}}><Pressable onPress={()=>favorite(m)} style={{flex:1,borderWidth:1,borderColor:colors.border,borderRadius:12,paddingVertical:11,alignItems:'center'}}><Feather name="heart" size={17} color={isMediaFavorite('movie',String(m.id))?colors.destructive:colors.mutedForeground}/><Text style={{color:colors.foreground,fontSize:12,marginTop:4}}>{isMediaFavorite('movie',String(m.id))?'В избранном':'В избранное'}</Text></Pressable><AppButton icon="info" onPress={()=>router.push({pathname:'/movie/[id]',params:{id:String(m.id)}})}>Подробнее</AppButton></View></Card>)}</View></>}
  {mediaFavorites.filter(x=>x.kind==='movie').length>0&&<><SectionTitle title="Избранное"/><Card>{mediaFavorites.filter(x=>x.kind==='movie').map(x=><Pressable key={x.id} onPress={()=>router.push({pathname:'/movie/[id]',params:{id:x.id}})} style={{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:9}}>{x.image?<Image source={{uri:x.image}} style={{width:48,height:68,borderRadius:7}}/>:null}<View style={{flex:1}}><Text style={{color:colors.foreground,fontWeight:'600'}}>{x.title}</Text><Text style={{color:colors.mutedForeground,fontSize:12,marginTop:3}}>{x.subtitle}</Text></View><Feather name="chevron-right" size={18} color={colors.mutedForeground}/></Pressable>)}</Card></>}
  {mediaHistory.filter(x=>x.kind==='movie').length>0&&<><SectionTitle title="История"/><Card>{mediaHistory.filter(x=>x.kind==='movie').slice(0,8).map(x=><Pressable key={x.id} onPress={()=>router.push({pathname:'/movie/[id]',params:{id:x.id}})} style={{paddingVertical:9}}><Text style={{color:colors.foreground,fontWeight:'600'}}>{x.title}</Text><Text style={{color:colors.mutedForeground,fontSize:12,marginTop:3}}>{x.subtitle} · {new Date(x.playedAt).toLocaleDateString('ru-RU')}</Text></Pressable>)}</Card></>}
  <AppButton variant="secondary" icon="external-link" onPress={()=>Linking.openURL('https://www.themoviedb.org').catch(()=>undefined)}>Официальный TMDB</AppButton>
 </Screen>;
}
