import React, { useState } from 'react';
import { ActivityIndicator, Linking, Pressable, Text, View } from 'react-native';
import { Stack } from 'expo-router';
import { useColors } from '@/hooks/useColors';
import { AppButton, Card, Field, Screen, SectionTitle, styles } from '@/components/ui';
import { getAirQuality, getRates, getTechNews, searchBooks, searchMusic, searchShows, type AirQualityData, type BookResult, type MusicResult, type NewsResult, type Rate, type ShowResult } from '@/services/liveApi';

export default function OnlineScreen(){
 const colors=useColors(); const [loading,setLoading]=useState(false); const [rates,setRates]=useState<Rate[]>([]); const [air,setAir]=useState<AirQualityData|null>(null); const [news,setNews]=useState<NewsResult[]>([]); const [books,setBooks]=useState<BookResult[]>([]); const [shows,setShows]=useState<ShowResult[]>([]); const [music,setMusic]=useState<MusicResult[]>([]); const [query,setQuery]=useState('Harry Potter'); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [r,a,n,b,s,m]=await Promise.all([getRates('EUR'),getAirQuality(),getTechNews(6),searchBooks(query),searchShows(query),searchMusic(query)]);setRates(r);setAir(a);setNews(n);setBooks(b);setShows(s);setMusic(m);}catch(e){setError(e instanceof Error?e.message:'Не удалось получить данные');}finally{setLoading(false)}};
 return <><Stack.Screen options={{title:'Онлайн API',headerTintColor:colors.foreground,headerStyle:{backgroundColor:colors.background},headerShadowVisible:false}}/><Screen><Text style={[styles.eyebrow,{color:colors.primary}]}>REAL API</Text><Text style={[styles.sectionTitle,{color:colors.foreground,fontSize:32}]}>Живые данные</Text><Text style={{color:colors.mutedForeground,marginTop:6}}>Данные загружаются из реальных публичных API. При ошибке приложение не падает.</Text><AppButton icon="refresh-cw" onPress={load}>{loading?'Обновление…':'Обновить API'}</AppButton>{loading?<ActivityIndicator style={{marginTop:12}}/>:null}{error?<Card><Text style={{color:colors.destructive}}>Ошибка: {error}</Text></Card>:null}
 <SectionTitle title="Курсы валют · Frankfurter"/><Card>{rates.length?rates.map(x=><Text key={x.quote} style={{color:colors.foreground,paddingVertical:5}}>1 {x.base} = {x.rate} {x.quote} · {x.date}</Text>):<Text style={{color:colors.mutedForeground}}>Нажмите «Обновить API»</Text>}</Card>
 <SectionTitle title="Качество воздуха · Open-Meteo"/><Card><Text style={{color:colors.foreground}}>AQI (EU): {air?.europeanAqi ?? '—'}</Text><Text style={{color:colors.foreground,marginTop:5}}>PM2.5: {air?.pm25 ?? '—'} · PM10: {air?.pm10 ?? '—'}</Text></Card>
 <SectionTitle title="Поиск книг · Open Library"/><Field value={query} onChangeText={setQuery} placeholder="Название книги"/><AppButton variant="secondary" onPress={async()=>{setLoading(true);try{setBooks(await searchBooks(query))}finally{setLoading(false)}}}>Искать книги</AppButton>{books.slice(0,5).map(b=><Card key={b.key}><Text style={{color:colors.foreground,fontWeight:'700'}}>{b.title}</Text><Text style={{color:colors.mutedForeground,marginTop:4}}>{b.authors.join(', ')}{b.year?` · ${b.year}`:''}</Text></Card>)}
 <SectionTitle title="Фильмы/сериалы · TVmaze"/><AppButton variant="secondary" onPress={async()=>{setLoading(true);try{setShows(await searchShows(query))}finally{setLoading(false)}}}>Искать шоу</AppButton>{shows.slice(0,5).map(s=><Pressable key={s.id} onPress={()=>Linking.openURL(s.url)}><Card><Text style={{color:colors.foreground,fontWeight:'700'}}>{s.name}</Text><Text style={{color:colors.mutedForeground,marginTop:4}}>{s.language ?? '—'}{s.premiered?` · ${s.premiered}`:''}</Text></Card></Pressable>)}
 <SectionTitle title="Музыка · Apple iTunes Search"/><AppButton variant="secondary" onPress={async()=>{setLoading(true);try{setMusic(await searchMusic(query))}finally{setLoading(false)}}}>Искать музыку</AppButton>{music.slice(0,5).map(m=><Pressable key={m.url} onPress={()=>Linking.openURL(m.url)}><Card><Text style={{color:colors.foreground,fontWeight:'700'}}>{m.track}</Text><Text style={{color:colors.mutedForeground,marginTop:4}}>{m.artist} · {m.album}</Text></Card></Pressable>)}
 <SectionTitle title="Новости · Hacker News"/>{news.map(n=><Pressable key={n.url} onPress={()=>Linking.openURL(n.url)}><Card><Text style={{color:colors.foreground,fontWeight:'700'}}>{n.title}</Text><Text style={{color:colors.mutedForeground,marginTop:4}}>score {n.score}</Text></Card></Pressable>)}
 </Screen></>;
}
